"use client";

import { useQuery } from "@tanstack/react-query";
import {
  HandCoins,
  KeyRound,
  type LucideIcon,
  Minus,
  Puzzle,
  Rocket,
  ShieldCheck,
  Users,
} from "lucide-react";
import { type Address, type Hex, keccak256, toHex } from "viem";
import { useChain } from "@/context/chain";
import { indexerUrlFor } from "@/lib/indexer";

/**
 * Collectives the connected account has a stake in.
 *
 * Queried straight against the indexer rather than through the SDK client. The
 * SDK's types are generated by graphql-codegen from a RUNNING ponder instance
 * (see packages/sdk/codegen.yml), so the collective tables cannot appear in
 * `@0xslots/sdk` until someone runs codegen against an indexer that has them.
 * Rather than ship a build that only typechecks after that step, this reads the
 * endpoint directly and declares its own row type.
 *
 * Move it into the SDK once codegen has run — the query below is already shaped
 * like the documents in packages/sdk/src/queries.
 */

/**
 * Why a collective is listed for you, as something renderable.
 *
 * Carries its own icon and tint rather than a bare label, because the summary
 * row shows these as icons alone. An icon with no accompanying text has to
 * supply its own accessible name, so `title` travels with it and is used for
 * both the tooltip and the aria-label — the name can never drift from the glyph.
 */
export interface Relation {
  /** Stable react key, and the dedup identity. */
  key: string;
  /** Full sentence: what this badge means. */
  title: string;
  icon: LucideIcon;
  tint: string;
  /** Sort position, so badge order is stable across rows. */
  rank: number;
}

export interface CollectiveRow {
  id: Address;
  chainId: number;
  admin: Address;
  deployer: Address;
  totalAllocation: string;
  splitRecipientCount: number;
  paused: boolean;
  createdAt: string;
  createdTx: string;
  /** Why this collective is listed for you. Derived client-side. */
  relation: Relation[];
}

interface RoleRow {
  collective: Address;
  role: string;
  label: string | null;
}

/**
 * The five roles a collective carries, in the order they are worth reading.
 *
 * Icon and tint are lifted from `app/create/sections.ts` rather than chosen
 * fresh, and the mapping is not decorative: each role governs exactly one of
 * the dimensions that form sets, so it inherits that section's colour. A tax
 * manager wears the same amber as the tax field they can change, a policy
 * manager the same violet as Occupancy. Someone who has used the create form
 * already knows what these mean.
 *
 * Keyed by the `label` the indexer writes (`SlotCollective`'s role constants
 * with `_ROLE` stripped, plus AccessControl's implicit admin).
 */
export interface RoleMeta {
  label: string;
  title: string;
  /** What the holder may actually do. */
  can: string;
  /**
   * The `bytes32` AccessControl identifies this role by.
   *
   * Derived here rather than read off an indexed row, because a role with NO
   * current holders has no row — and that is exactly when you most need to
   * grant one. `DEFAULT_ADMIN_ROLE` is bytes32(0); the rest are
   * `keccak256("<NAME>_ROLE")`, matching the constants in SlotCollective.sol.
   */
  hash: Hex;
  icon: LucideIcon;
  tint: string;
}

/** Mirrors `keccak256("X_ROLE")` in Solidity. */
const roleHash = (name: string): Hex => keccak256(toHex(name));

export const COLLECTIVE_ROLES: RoleMeta[] = [
  {
    label: "DEFAULT_ADMIN",
    title: "Admin",
    can: "Everything below, plus granting and revoking these roles.",
    hash: `0x${"0".repeat(64)}`,
    icon: KeyRound,
    tint: "bg-rose-500/10 text-rose-600 dark:text-rose-400",
  },
  {
    label: "TAX_MANAGER",
    title: "Tax",
    can: "Change the tax rate and the liquidation bounty.",
    hash: roleHash("TAX_MANAGER_ROLE"),
    icon: HandCoins,
    tint: "bg-amber-500/10 text-amber-600 dark:text-amber-400",
  },
  {
    label: "POLICY_MANAGER",
    title: "Policy",
    can: "Change who is allowed to hold the slot.",
    hash: roleHash("POLICY_MANAGER_ROLE"),
    icon: ShieldCheck,
    tint: "bg-violet-500/10 text-violet-600 dark:text-violet-400",
  },
  {
    label: "UTILITY_MANAGER",
    title: "Utility",
    can: "Change what holding the slot grants.",
    hash: roleHash("UTILITY_MANAGER_ROLE"),
    icon: Puzzle,
    tint: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
  },
  {
    label: "SPLIT_MANAGER",
    title: "Split",
    can: "Rewrite the payouts, and pause distribution.",
    hash: roleHash("SPLIT_MANAGER_ROLE"),
    icon: Users,
    tint: "bg-sky-500/10 text-sky-600 dark:text-sky-400",
  },
];

/**
 * Deploying is history, not authority.
 *
 * Ranked after every role and tinted neutral so it never reads as a power —
 * the address that created a collective may hold nothing in it today.
 */
const DEPLOYER_RELATION: Relation = {
  key: "deployer",
  title: "Deployer — you created this collective",
  icon: Rocket,
  tint: "bg-muted text-muted-foreground",
  rank: 90,
};

/** Listed, but you hold nothing here. */
const NO_ROLE_RELATION: Relation = {
  key: "none",
  title: "No role — you hold nothing on this collective",
  icon: Minus,
  tint: "bg-muted text-muted-foreground",
  rank: 99,
};

export interface RoleMember {
  account: Address;
  grantedAt: string | null;
}

/** One row per role, with its current holders. Empty lists are kept. */
export interface RoleGroup extends RoleMeta {
  members: RoleMember[];
}

/** A payee on the collective's current split. */
export interface SplitRecipient {
  index: number;
  account: Address;
  allocation: string;
  shareBps: number;
}

export interface CollectiveDetail {
  id: Address;
  chainId: number;
  admin: Address;
  deployer: Address;
  totalAllocation: string;
  splitRecipientCount: number;
  paused: boolean;
  createdAt: string;
  createdTx: string;
  recipients: SplitRecipient[];
}

const DETAIL_QUERY = /* GraphQL */ `
  query Collective($id: String!) {
    slotCollective(id: $id) {
      id
      chainId
      admin
      deployer
      totalAllocation
      splitRecipientCount
      paused
      createdAt
      createdTx
    }
    collectiveSplitRecipients(where: { collective: $id }, limit: 200) {
      items {
        index
        account
        allocation
        shareBps
      }
    }
  }
`;

/**
 * One collective, addressed by the URL.
 *
 * Returns `null` — not an error — when the address is well-formed but unknown
 * to the indexer. That is an ordinary outcome worth distinguishing: a
 * collective created seconds ago has not been indexed yet, and a page that
 * threw would tell the user it was broken rather than that it was early.
 */
export function useCollective(address: string | undefined) {
  const { chainId } = useChain();
  const id = address?.toLowerCase();

  return useQuery({
    queryKey: ["collective", chainId, id],
    enabled: !!id,
    queryFn: async (): Promise<CollectiveDetail | null> => {
      const res = await fetch(indexerUrlFor(chainId), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: DETAIL_QUERY, variables: { id } }),
      });
      if (!res.ok) throw new Error(`Indexer ${res.status}`);

      const json = await res.json();
      if (json.errors?.length) {
        throw new Error(json.errors[0]?.message ?? "Query failed");
      }

      const row = json.data?.slotCollective;
      if (!row) return null;

      // Ordered by position, matching the on-chain array the allocations were
      // validated against.
      const recipients: SplitRecipient[] = (
        json.data?.collectiveSplitRecipients?.items ?? []
      ).sort((a: SplitRecipient, b: SplitRecipient) => a.index - b.index);

      return { ...row, recipients };
    },
  });
}

const ROLES_QUERY = /* GraphQL */ `
  query CollectiveRoles($collective: String!) {
    collectiveRoles(
      where: { collective: $collective, granted: true }
      limit: 200
    ) {
      items {
        role
        account
        label
        grantedAt
      }
    }
  }
`;

/**
 * Every role holder on one collective.
 *
 * `enabled` exists because this used to power an inline drawer in the list,
 * where twenty rows would otherwise have issued twenty queries for detail nobody
 * had asked to see. The detail page passes `true` — it is the whole reason the
 * page was opened.
 */
export function useCollectiveRoles(
  collective: Address | undefined,
  enabled: boolean,
) {
  const { chainId } = useChain();

  return useQuery({
    queryKey: ["collective-roles", chainId, collective],
    enabled: enabled && !!collective,
    queryFn: async (): Promise<RoleGroup[]> => {
      const res = await fetch(indexerUrlFor(chainId), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query: ROLES_QUERY,
          variables: { collective: collective?.toLowerCase() },
        }),
      });
      if (!res.ok) throw new Error(`Indexer ${res.status}`);

      const json = await res.json();
      if (json.errors?.length) {
        throw new Error(json.errors[0]?.message ?? "Query failed");
      }

      const items: {
        role: string;
        account: Address;
        label: string | null;
        grantedAt: string | null;
      }[] = json.data?.collectiveRoles?.items ?? [];

      // Grouped against the known five rather than whatever came back, so the
      // order is stable and an empty role still renders — "nobody holds this"
      // is information, and a role that silently vanished would read as though
      // the dimension were ungoverned rather than admin-only.
      return COLLECTIVE_ROLES.map((meta) => ({
        ...meta,
        members: items
          .filter((i) => i.label === meta.label)
          .map(({ account, grantedAt }) => ({ account, grantedAt })),
      }));
    },
  });
}

interface RawCollective extends Omit<CollectiveRow, "relation"> {}

/**
 * One request, three aliases.
 *
 * "Deployed by me" and "admin is me" are two different columns, and role
 * membership is a separate table because `admin` can move after deployment —
 * the founding admin is not necessarily the current one. Fetching all three
 * together keeps it to a single round trip and lets the merge below explain
 * WHY each row is listed.
 */
const QUERY = /* GraphQL */ `
  query MyCollectives($chainId: Int!, $me: String!) {
    deployed: slotCollectives(
      where: { chainId: $chainId, deployer: $me }
      limit: 100
    ) {
      items {
        id
        chainId
        admin
        deployer
        totalAllocation
        splitRecipientCount
        paused
        createdAt
        createdTx
      }
    }
    administered: slotCollectives(
      where: { chainId: $chainId, admin: $me }
      limit: 100
    ) {
      items {
        id
        chainId
        admin
        deployer
        totalAllocation
        splitRecipientCount
        paused
        createdAt
        createdTx
      }
    }
    roles: collectiveRoles(
      where: { chainId: $chainId, account: $me, granted: true }
      limit: 200
    ) {
      items {
        collective
        role
        label
      }
    }
  }
`;

export function useMyCollectives(account: Address | undefined) {
  const { chainId } = useChain();

  return useQuery({
    queryKey: ["my-collectives", chainId, account?.toLowerCase()],
    enabled: !!account,
    queryFn: async (): Promise<CollectiveRow[]> => {
      const res = await fetch(indexerUrlFor(chainId), {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query: QUERY,
          // Addresses are stored lowercased by every handler, and GraphQL
          // equality is exact — a checksummed address matches nothing.
          variables: { chainId, me: account?.toLowerCase() },
        }),
      });
      if (!res.ok) throw new Error(`Indexer ${res.status}`);

      const json = await res.json();
      if (json.errors?.length) {
        throw new Error(json.errors[0]?.message ?? "Query failed");
      }

      const deployed: RawCollective[] = json.data?.deployed?.items ?? [];
      const administered: RawCollective[] =
        json.data?.administered?.items ?? [];
      const roles: RoleRow[] = json.data?.roles?.items ?? [];

      // Merge the three sources into one row per collective, carrying the
      // reasons rather than collapsing them — "you deployed this" and "you run
      // its tax" are different facts and both are worth showing.
      const byId = new Map<string, CollectiveRow>();

      // `reason` may be null: the row is worth LISTING but that fact says
      // nothing about present authority.
      const add = (row: RawCollective, reason: Relation | null) => {
        const existing = byId.get(row.id);
        if (existing) {
          if (reason && !existing.relation.some((r) => r.key === reason.key)) {
            existing.relation.push(reason);
          }
          return;
        }
        byId.set(row.id, { ...row, relation: reason ? [reason] : [] });
      };

      // Deploying is a permanent historical fact, so it is a badge.
      for (const row of deployed) add(row, DEPLOYER_RELATION);

      // `slotCollective.admin` is DISCOVERY ONLY, deliberately unlabelled.
      //
      // It records the DEFAULT_ADMIN_ROLE holder at deployment and is never
      // updated — the schema says as much, and roles move afterwards. Badging it
      // "Admin" meant that revoking your own admin left the row still claiming
      // you were one, permanently and with no way to clear it. It is still worth
      // querying, because it is how a collective someone else deployed for you
      // gets found at all.
      for (const row of administered) add(row, null);

      // The live answer. Everything the badges assert about present authority
      // comes from here, so a grant or revoke is reflected as soon as the
      // indexer sees the event.
      for (const { collective, label } of roles) {
        const row = byId.get(collective);
        if (!row || !label) continue;
        const idx = COLLECTIVE_ROLES.findIndex((m) => m.label === label);
        const meta = COLLECTIVE_ROLES[idx];
        if (!meta) continue;
        if (row.relation.some((r) => r.key === meta.label)) continue;
        row.relation.push({
          key: meta.label,
          // The row shows this as an icon alone, so the name has to say what
          // the glyph cannot: which role, and what it lets you do.
          title:
            meta.label === "DEFAULT_ADMIN"
              ? `Admin — ${meta.can}`
              : `${meta.title} manager — ${meta.can}`,
          icon: meta.icon,
          tint: meta.tint,
          rank: idx,
        });
      }

      // Listed but holding nothing — the founding admin who revoked themselves,
      // typically. Saying so beats an empty cell that reads as a render bug.
      for (const row of byId.values()) {
        if (row.relation.length === 0) row.relation.push(NO_ROLE_RELATION);
        // Stable order regardless of which query found what: Admin, then the
        // four managers, then Deployer, then the empty case.
        row.relation.sort((a, b) => a.rank - b.rank);
      }

      return [...byId.values()].sort(
        (a, b) => Number(b.createdAt) - Number(a.createdAt),
      );
    },
  });
}
